/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/AanwezigVliegtuigen/CreateTable": {
    post: {
      parameters: {
        query: {
          /** Dummy records aanmaken */
          FILLDATA: boolean;
        };
      };
      responses: {
        /** Aangemaakt, Tabel toegevoegd */
        201: unknown;
        /** Data verwerkingsfout, bijv omdat de tabel al bestaat */
        500: unknown;
      };
    };
  };
  "/AanwezigVliegtuigen/CreateViews": {
    post: {
      responses: {
        /** Aangemaakt, View toegevoegd */
        201: unknown;
        /** Data verwerkingsfout, view niet aangemaak */
        500: unknown;
      };
    };
  };
  "/AanwezigVliegtuigen/GetObject": {
    get: {
      parameters: {
        query: {
          /** Database ID van het aanwezig record */
          ID?: number;
          /** Vliegtuig ID (ID uit ref_vliegtuigen). Werkt alleen als ID null is. Bovendien is DATUM vereist */
          VLIEGTUIG_ID?: number;
          /** DATUM van de vliegdag. Werkt alleen als ID null is. Bovendien is LID_ID vereist */
          DATUM?: string;
          /** Toon alleen vliegtuigen die nog niet vertrokken zijn */
          NIET_VERTROKKEN?: boolean;
        };
      };
      responses: {
        /** OK, data succesvol opgehaald */
        200: {
          content: {
            "application/json": components["schemas"]["oper_aanwezig_vliegtuigen"];
          };
        };
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/AanwezigVliegtuigen/GetObjects": {
    get: {
      parameters: {
        query: {
          /** Database ID van het aanwezig record */
          ID?: number;
          /** Toon welke records verwijderd zijn. Default = false */
          VERWIJDERD?: boolean;
          /** Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg */
          LAATSTE_AANPASSING?: boolean;
          /** HASH van laatste GetObjects aanroep. Indien bij nieuwe aanroep dezelfde data bevat, dan volgt http status code 304. In geval dataset niet hetzelfde is, dan komt de nieuwe dataset terug. Ook bedoeld om dataverbruik te vermindereren. Er wordt alleen data verzonden als het nodig is. */
          HASH?: string;
          /** Sortering van de velden in ORDER BY formaat. Default = NAAM */
          SORT?: string;
          /** Maximum aantal records in de dataset. Gebruikt in LIMIT query */
          MAX?: number;
          /** Eerste record in de dataset. Gebruikt in LIMIT query */
          START?: number;
          /** Welke velden moet opgenomen worden in de dataset */
          VELDEN?: string;
          /** Zoek in de NAAM van de aanwezige */
          SELECTIE?: string;
          /** Een of meerdere vliegtuigen database IDs in CSV formaat. AND conditie als er geen andere parameters zijn, anders OR conditie */
          IN?: string;
          /** Begin datum (inclusief deze dag) */
          BEGIN_DATUM?: string;
          /** Eind datum (inclusief deze dag) */
          EIND_DATUM?: string;
        };
      };
      responses: {
        /** OK, data succesvol opgehaald */
        200: {
          content: {
            "application/json": components["schemas"]["view_aanwezig_vliegtuigen"];
          };
        };
        /** Data niet gemodificeerd, HASH in aanroep == hash in dataset */
        304: never;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/AanwezigVliegtuigen/Aanmelden": {
    post: {
      responses: {
        /** OK, data succesvol aangepast */
        200: {
          content: {
            "application/json": components["schemas"]["oper_aanwezig_vliegtuigen"];
          };
        };
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
      /** Lid data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["oper_aanwezig_vliegtuigen_in"] & {
            /**
             * Format: date-time
             * @description Tijdstip van de aanmelding. Indien afwezig, huidige tijd. ISO8601
             * @example 2018-03-22T10:32:28Z
             */
            TIJDSTIP?: string;
          };
        };
      };
    };
  };
  "/AanwezigVliegtuigen/Afmelden": {
    post: {
      responses: {
        /** OK, data succesvol aangepast */
        200: {
          content: {
            "application/json": components["schemas"]["oper_aanwezig_vliegtuigen"];
          };
        };
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Lid is niet aanwezig */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
      /** Lid data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["oper_aanwezig_vliegtuigen_in"] & {
            /**
             * Format: date-time
             * @description Tijdstip van de afmelding. Indien afwezig, huidige tijd. ISO8601
             * @example 2017-07-21T09:32:28Z
             */
            TIJDSTIP?: string;
          };
        };
      };
    };
  };
  "/AanwezigVliegtuigen/DeleteObject": {
    delete: {
      parameters: {
        query: {
          /** Database ID van het aanwezig record. Meerdere ID's in CSV formaat */
          ID?: string;
          /** Datum van de vliegdag */
          DATUM?: string;
          /** Het vliegtuig ID. Verwijzing naar vliegtuigen tabel */
          VLIEGTUIG_ID?: number;
          /** Controleer of record bestaat voordat het verwijderd wordt. Default = true */
          VERIFICATIE?: boolean;
        };
      };
      responses: {
        /** Aanwezig record verwijderd */
        204: never;
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/AanwezigVliegtuigen/RestoreObject": {
    patch: {
      parameters: {
        query: {
          /** Database ID van het record. Meerdere ID's in CSV formaat */
          ID: string;
        };
      };
      responses: {
        /** Record(s) hersteld */
        202: unknown;
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/AanwezigVliegtuigen/SaveObject": {
    put: {
      responses: {
        /** OK, data succesvol aangepast */
        200: {
          content: {
            "application/json": components["schemas"]["oper_aanwezig_vliegtuigen"];
          };
        };
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Conflict, lid is al/niet aanwezig op deze dag */
        409: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
      /** Aanmelding data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["oper_aanwezig_vliegtuigen_in"];
        };
      };
    };
    post: {
      responses: {
        /** OK, data succesvol toegevoegd */
        200: {
          content: {
            "application/json": components["schemas"]["oper_aanwezig_vliegtuigen"];
          };
        };
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Conflict, lid is al aanwezig */
        409: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
      /** Aanmelding data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["oper_aanwezig_vliegtuigen_in"];
        };
      };
    };
  };
}

export interface components {
  schemas: {
    oper_aanwezig_vliegtuigen_in: {
      /**
       * Format: int32
       * @description Database ID van het aanwezig record
       * @example 12871
       */
      ID?: number;
      /**
       * Format: date
       * @description Datum van de vliegdag
       * @example 2017-07-21
       */
      DATUM?: string;
      /**
       * @description Het vliegtuig ID. Verwijzing naar vliegtuigen tabel
       * @example 215
       */
      VLIEGTUIG_ID?: number;
      /**
       * @description Aankomsttijd van het vliegtuig. ISO8601
       * @example 09:32:28
       */
      AANKOMST?: string;
      /**
       * @description Vertrektijd van het vliegtuig. ISO8601
       * @example 17:32:28
       */
      VERTREK?: string;
      /**
       * Format: double
       * @description Positie van het vliegtuig in latitude
       * @example 52.11231
       */
      LATITUDE?: number;
      /**
       * Format: double
       * @description Positie van het vliegtuig in longitude
       * @example 4.61754
       */
      LONGITUDE?: number;
      /**
       * Format: int
       * @description Hoogte van het vliegtuig in meters
       * @example 694
       */
      HOOGTE?: number;
      /**
       * Format: int
       * @description Snelheid van het vliegtuig in km/h
       * @example 95
       */
      SNELHEID?: number;
      /**
       * @description Op welk veld is dit vliegtuig aangemeld
       * @example 901
       */
      VELD_ID?: number;
    };
    oper_aanwezig_vliegtuigen: components["schemas"]["oper_aanwezig_vliegtuigen_in"] & {
      /**
       * @description Is dit record gemarkeerd als verwijderd?
       * @example 0
       */
      VERWIJDERD?: boolean;
      /**
       * Format: date-time
       * @description Tijdstempel van laaste aanpassing in de database
       * @example 2020-09-18 09:51:16
       */
      LAATSTE_AANPASSING?: string;
    };
    view_aanwezig_vliegtuigen_dataset: components["schemas"]["oper_aanwezig_vliegtuigen"] & {
      /**
       * @description Het registratie nummer van het vliegtuig
       * @example PH-1234
       */
      REGISTRATIE?: string;
      /**
       * @description Optioneel het callsign van het vliegtuig
       * @example AA
       */
      CALLSIGN?: string;
      /**
       * @description De flarmcode zoals deze wordt uitgezonden. Zo kunnen we ontvangen flarm data herleiden naar een vliegtuig uit de database
       * @example 123456
       */
      FLARMCODE?: string;
      /**
       * Format: int32
       * @description Het aantal zitplaatsen. Is 1 of 2.
       * @example 1
       */
      ZITPLAATSEN?: number;
      /**
       * @description Kan het vliegtuig op eigen kracht starten.
       * @example 0
       */
      ZELFSTART?: boolean;
      /**
       * @description Is het een club vliegtuig?
       * @example 1
       */
      CLUBKIST?: boolean;
      /**
       * @description Is het een TMG?
       * @example 0
       */
      TMG?: boolean;
      /**
       * @description Is het een sleepvliegtuig?
       * @example 0
       */
      SLEEPKIST?: boolean;
      /**
       * Format: int32
       * @description Link naar vliegtuig type tabel. Alleen nodig voor clubvliegtuigen
       * @example 12
       */
      TYPE_ID?: number;
      /**
       * @description Vliegtuigtype omschrijving
       * @example ASK21
       */
      VLIEGTUIGTYPE_OMS?: string;
      /**
       * Format: int32
       * @description Volgorde van vliegtuiglijst, bedoeld voor club vliegtuigen
       * @example 12
       */
      VOLGORDE?: number;
      /**
       * @description Mag het vliegtuig vliegen?
       * @example true
       */
      INZETBAAR?: boolean;
      /**
       * @description Is het vliegtuig een DBO trainer
       * @example true
       */
      TRAINER?: boolean;
      /**
       * @description Vliegt het lid op dit moment
       * @example true
       */
      VLIEGT?: boolean;
      /**
       * @description Opermerkingen over vliegtuig
       * @example Radio op stand 10 zetten
       */
      OPMERKINGEN?: string;
      /**
       * @description Vliegveld waar vliegtuig aangemeld is
       * @example Terlet
       */
      VELD?: string;
      /**
       * @description Vliegtuig registratie en callsign van het vliegtuig
       * @example PH-1076 (E2)
       */
      REG_CALL?: string;
    };
    view_aanwezig_vliegtuigen: {
      /**
       * Format: int32
       * @description Aantal records dat voldoet aan de criteria in de database
       * @example 287
       */
      totaal?: number;
      /**
       * Format: date-time
       * @description Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria
       * @example 2013-04-20 08:01:00
       */
      laatste_aanpassing?: string;
      /**
       * @description hash van de dataset
       * @example 4d00b3f
       */
      hash?: string;
      /** @description De dataset met records */
      dataset?: components["schemas"]["view_aanwezig_vliegtuigen_dataset"][];
    };
  };
}

export interface operations {}

export interface external {}
