/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/AanwezigLeden/CreateTable": {
    post: {
      parameters: {
        query: {
          /** Dummy records aanmaken */
          FILLDATA: boolean;
        };
      };
      responses: {
        /** Aangemaakt, Tabel toegevoegd */
        201: unknown;
        /** Data verwerkingsfout, bijv omdat de tabel al bestaat */
        500: unknown;
      };
    };
  };
  "/AanwezigLeden/CreateViews": {
    post: {
      responses: {
        /** Aangemaakt, View toegevoegd */
        201: unknown;
        /** Data verwerkingsfout, view niet aangemaak */
        500: unknown;
      };
    };
  };
  "/AanwezigLeden/GetObject": {
    get: {
      parameters: {
        query: {
          /** Database ID van het aanwezig record */
          ID?: number;
          /** Lid ID (ID uit ref_leden). Werkt alleen als ID null is. Bovendien is DATUM vereist */
          LID_ID?: number;
          /** DATUM van de vliegdag. Werkt alleen als ID null is. Bovendien is LID_ID vereist */
          DATUM?: string;
        };
      };
      responses: {
        /** OK, data succesvol opgehaald */
        200: {
          content: {
            "application/json": components["schemas"]["oper_aanwezig_leden"];
          };
        };
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/AanwezigLeden/GetObjects": {
    get: {
      parameters: {
        query: {
          /** Database ID van het aanwezig record */
          ID?: number;
          /** Toon welke records verwijderd zijn. Default = false */
          VERWIJDERD?: boolean;
          /** Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg */
          LAATSTE_AANPASSING?: boolean;
          /** HASH van laatste GetObjects aanroep. Indien bij nieuwe aanroep dezelfde data bevat, dan volgt http status code 304. In geval dataset niet hetzelfde is, dan komt de nieuwe dataset terug. Ook bedoeld om dataverbruik te vermindereren. Er wordt alleen data verzonden als het nodig is. */
          HASH?: string;
          /** Sortering van de velden in ORDER BY formaat. Default = NAAM */
          SORT?: string;
          /** Maximum aantal records in de dataset. Gebruikt in LIMIT query */
          MAX?: number;
          /** Eerste record in de dataset. Gebruikt in LIMIT query */
          START?: number;
          /** Welke velden moet opgenomen worden in de dataset */
          VELDEN?: string;
          /** Zoek in de NAAM van de aanwezige */
          SELECTIE?: string;
          /** Een of meerdere leden database IDs in CSV formaat. AND conditie als er geen andere parameters zijn, anders OR conditie */
          IN?: string;
          /** Zoek op een of meerder lid types. Types als CSV formaat */
          TYPES?: string;
          /** Begin datum (inclusief deze dag) */
          BEGIN_DATUM?: string;
          /** Eind datum (inclusief deze dag) */
          EIND_DATUM?: string;
          /** Toon alleen leden die nog niet vertrokken zijn */
          NIET_VERTROKKEN?: boolean;
        };
      };
      responses: {
        /** OK, data succesvol opgehaald */
        200: {
          content: {
            "application/json": components["schemas"]["view_aanwezig_leden"];
          };
        };
        /** Data niet gemodificeerd, HASH in aanroep == hash in dataset */
        304: never;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/AanwezigLeden/Aanmelden": {
    post: {
      responses: {
        /** OK, data succesvol aangepast */
        200: {
          content: {
            "application/json": components["schemas"]["oper_aanwezig_leden"];
          };
        };
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
      /** Lid data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["oper_aanwezig_leden_in"] & {
            /**
             * Format: date-time
             * @description Tijdstip van de aanmelding. Indien afwezig, huidige tijd. ISO8601
             * @example 2017-07-21T09:32:28Z
             */
            TIJDSTIP?: string;
          };
        };
      };
    };
  };
  "/AanwezigLeden/Afmelden": {
    post: {
      responses: {
        /** OK, data succesvol aangepast */
        200: {
          content: {
            "application/json": components["schemas"]["oper_aanwezig_leden"];
          };
        };
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Lid is niet aanwezig */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
      /** Lid data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["oper_aanwezig_leden_in"] & {
            /**
             * Format: date-time
             * @description Tijdstip van de afmelding. Indien afwezig, huidige tijd. ISO8601
             * @example 2018-07-21T17:00:32Z
             */
            TIJDSTIP?: string;
          };
        };
      };
    };
  };
  "/AanwezigLeden/Samenvattting": {
    get: {
      parameters: {
        query: {
          /** DATUM van de vliegdag. */
          DATUM?: string;
        };
      };
      responses: {
        /** OK, data succesvol opgehaald */
        200: {
          content: {
            "application/json": components["schemas"]["samenvatting"];
          };
        };
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/AanwezigLeden/PotentieelVliegers": {
    get: {
      parameters: {
        query: {
          /** Het vliegtuig ID. Verwijzing naar vliegtuigen tabel */
          VLIEGTUID_ID: number;
          /** DATUM van de vliegdag. */
          DATUM?: string;
        };
      };
      responses: {
        /** OK, data succesvol opgehaald */
        200: {
          content: {
            "application/json": components["schemas"]["oper_vliegers"];
          };
        };
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
      };
    };
  };
  "/AanwezigLeden/DeleteObject": {
    delete: {
      parameters: {
        query: {
          /** Database ID van het aanwezig record. Meerdere ID's in CSV formaat */
          ID?: string;
          /** Datum van de vliegdag */
          DATUM?: string;
          /** Het lid ID. Verwijzing naar leden tabel */
          LID_ID?: number;
          /** Controleer of record bestaat voordat het verwijderd wordt. Default = true */
          VERIFICATIE?: boolean;
        };
      };
      responses: {
        /** Aanwezig record verwijderd */
        204: never;
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/AanwezigLeden/RestoreObject": {
    patch: {
      parameters: {
        query: {
          /** Database ID van het record. Meerdere ID's in CSV formaat */
          ID: string;
        };
      };
      responses: {
        /** Record(s) hersteld */
        202: unknown;
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/AanwezigLeden/SaveObject": {
    put: {
      responses: {
        /** OK, data succesvol aangepast */
        200: {
          content: {
            "application/json": components["schemas"]["oper_aanwezig_leden"];
          };
        };
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Conflict, lid is al/niet aanwezig op deze dag */
        409: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
      /** Aanmelding data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["oper_aanwezig_leden_in"];
        };
      };
    };
    post: {
      responses: {
        /** OK, data succesvol toegevoegd */
        200: {
          content: {
            "application/json": components["schemas"]["oper_aanwezig_leden"];
          };
        };
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Conflict, lid is al aanwezig */
        409: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
      /** Aanmelding data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["oper_aanwezig_leden_in"];
        };
      };
    };
  };
}

export interface components {
  schemas: {
    oper_aanwezig_leden_in: {
      /**
       * Format: int32
       * @description Database ID van het aanwezig record
       * @example 12871
       */
      ID?: number;
      /**
       * Format: date
       * @description Datum van de vliegdag
       * @example 2017-07-21
       */
      DATUM?: string;
      /**
       * @description De positie op de startlijst. Nummer 1 is staat hoger op de startlijst als nummer 2
       * @example 12
       */
      POSITIE?: number;
      /**
       * @description Het lid ID. Verwijzing naar leden tabel
       * @example 10408
       */
      LID_ID?: number;
      /**
       * @description Heeft het lid zich vooraf aangemeld (bijv ingeschreven via DDWV)?
       * @example 0
       */
      VOORAANMELDING?: boolean;
      /**
       * @description Aankomsttijd van het lid. ISO8601
       * @example 09:32:28
       */
      AANKOMST?: string;
      /**
       * @description Vertrektijd van het lid. ISO8601
       * @example 17:32:28
       */
      VERTREK?: string;
      /**
       * Format: int32
       * @description Lid wil graag overland met dit vliegtuig. Verwijzing naar vliegtuig tabel
       * @example 200
       */
      OVERLAND_VLIEGTUIG_ID?: number;
      /**
       * @description Op welke type wil dit lid vandaag vliegen? Types als CSV formaat
       * @example 404, 405
       */
      VOORKEUR_VLIEGTUIG_TYPE?: string;
      /**
       * @description Op welk veld is dit lid aangemeld
       * @example 901
       */
      VELD_ID?: number;
      /**
       * Format: int32
       * @description Transactie voor betaling DDWV
       * @example 2001
       */
      TRANSACTIE_ID?: number;
      /**
       * @description Opmerking over de vliegdag
       * @example Heeft in de ochtend lierdienst
       */
      OPMERKINGEN?: string;
    };
    oper_aanwezig_leden: components["schemas"]["oper_aanwezig_leden_in"] & {
      /**
       * @description Is dit record gemarkeerd als verwijderd?
       * @example 0
       */
      VERWIJDERD?: boolean;
      /**
       * Format: date-time
       * @description Tijdstempel van laaste aanpassing in de database
       * @example 2015-01-21 11:52:22
       */
      LAATSTE_AANPASSING?: string;
    };
    view_aanwezig_leden_dataset: components["schemas"]["oper_aanwezig_leden"] & {
      /**
       * @description Korte beschrijving van het vliegtuig types
       * @example DCS, Duo
       */
      VLIEGTUIGTYPE_CODE?: string;
      /**
       * @description Beschrijving van het vliegtuig types
       * @example Discus CS, Duo Discus
       */
      VLIEGTUIGTYPE_OMS?: string;
      /**
       * @description Vliegtuig registratie en callsign van overland vliegtuig
       * @example PH-1076 (E2)
       */
      REG_CALL?: string;
      /**
       * @description Het aantal starts voor dit lid op deze dag
       * @example 3
       */
      STARTS?: number;
      /**
       * @description Totale vliegtijd
       * @example 03:17
       */
      VLIEGTIJD?: string;
      /**
       * @description Vliegt het lid op dit moment
       * @example true
       */
      VLIEGT?: boolean;
      /**
       * @description De volledige naam van het lid
       * @example Meindert het Paard
       */
      NAAM?: string;
      /**
       * @description De voornaam van het lid
       * @example Meindert
       */
      VOORNAAM?: string;
      /**
       * @description De tussenvoegsel van het lid
       * @example het
       */
      TUSSENVOEGSEL?: string;
      /**
       * @description De achternaam van het lid zonder tussenvoegsels
       * @example Paard
       */
      ACHTERNAAM?: string;
      /**
       * @description Het (post) adres waar het lid woont
       * @example Werf 18
       */
      ADRES?: string;
      /**
       * @description De postcode die bij het adres hoort
       * @example 7158 PP
       */
      POSTCODE?: string;
      /**
       * @description De plaatsnaam
       * @example Berkum
       */
      WOONPLAATS?: string;
      /**
       * @description Telefoon nummer van het lid
       * @example 086-1506822
       */
      TELEFOON?: string;
      /**
       * @description Mobiel telefoon nummer van het lid
       * @example 06-1025500
       */
      MOBIEL?: string;
      /**
       * @description Het telefoonnummer van een naaste, kan gebruikt worden in noodgevallen
       * @example 0112-11801
       */
      NOODNUMMER?: string;
      /**
       * @description email adres van het lid
       * @example meindert@fabeltje.com
       */
      EMAIL?: string;
      /**
       * @description Het lidnummer zoals dat in de leden administratie bekend is
       * @example 11139
       */
      LIDNR?: string;
      /**
       * Format: int32
       * @description Het soort lid (jeugdlid, lid, donateur). Verwijzing naar type tabel
       * @example 603
       */
      LIDTYPE_ID?: number;
      /**
       * @description Lid type omschrijving uit type tabel
       * @example Erlelid
       */
      LIDTYPE?: string;
      /**
       * Format: int32
       * @description Zusterclub lidmaatschap van lid. Nodig voor DDWV.
       * @example 603
       */
      ZUSTERCLUB_ID?: number;
      /**
       * @description Mag dit lid lieren?
       * @example 0
       */
      LIERIST?: boolean;
      /**
       * @description Kan dit lid het startbedrijf leiden?
       * @example 0
       */
      STARTLEIDER?: boolean;
      /**
       * @description Heeft dit lid een instructie bevoegdheid?
       * @example 0
       */
      INSTRUCTEUR?: boolean;
      /**
       * @description Werkt dit lid mee in het DDWV bedrijf
       * @example 0
       */
      DDWV_CREW?: boolean;
      /**
       * @description Is dit lid de beheerder van het DDWV bedrijf, heeft toegang tot DDWV gerelateede data
       * @example 0
       */
      DDWV_BEHEERDER?: boolean;
      /**
       * @description Is dit lid de beheerder van deze omgeving, heeft toegang tot alles
       * @example 0
       */
      BEHEERDER?: boolean;
      /**
       * @description Dit account wordt gebruikt om starts in de start toren in te voeren
       * @example 0
       */
      STARTTOREN?: boolean;
      /**
       * @description Is dit lid  belast met het maken van roosters
       * @example 0
       */
      ROOSTER?: boolean;
      /**
       * @description Moet clubblad per post verstuurd worden
       * @example false
       */
      CLUBBLAD_POST?: boolean;
      /**
       * Format: date
       * @description Verloopdatum van het medical
       * @example 2022-01-16
       */
      MEDICAL?: string;
      /**
       * Format: date
       * @description Geboorte datum van het lid
       * @example 1932-01-16
       */
      GEBOORTE_DATUM?: string;
      /**
       * @description De inlognaam van het lid
       * @example mpaard
       */
      INLOGNAAM?: string;
      /**
       * @description Readonly, URL om image op te halen. Zetten via UploadAvatar functie
       * @example 123456
       */
      AVATAR?: string;
      /**
       * @description Heef het lid deen startverbod?
       * @example 0
       */
      STARTVERBOD?: boolean;
      /**
       * @description Staat privacy mode (AVG / GDPR) uit/aan
       * @example 0
       */
      PRIVACY?: boolean;
      /**
       * Format: int32
       * @description De vliegstatus van het lid (DBO, solist, brevethouder), NULL indien niet van toepassing
       * @example 1901
       */
      STATUSTYPE_ID?: number;
      /**
       * @description Vliegstatus van aangemeld lid
       * @example Brevethouder
       */
      STATUS?: string;
      /**
       * @description Kleur van de barometer rood / geel / groen
       * @example rood
       */
      STATUS_BAROMETER?: string;
      /**
       * Format: int32
       * @description Volgorde in de HMI
       * @example 7
       */
      STATUS_SORTEER_VOLGORDE?: number;
      /**
       * @description Vliegveld waar lid aangemeld is
       * @example Terlet
       */
      VELD?: string;
    };
    view_aanwezig_leden: {
      /**
       * Format: int32
       * @description Aantal records dat voldoet aan de criteria in de database
       * @example 287
       */
      totaal?: number;
      /**
       * Format: date-time
       * @description Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria
       * @example 2020-05-11 09:38:00
       */
      laatste_aanpassing?: string;
      /**
       * @description hash van de dataset
       * @example 6d23bab
       */
      hash?: string;
      /** @description De dataset met records */
      dataset?: components["schemas"]["view_aanwezig_leden_dataset"][];
    };
    oper_vliegers: {
      /**
       * @description Het lid ID. Verwijzing naar leden tabel
       * @example 10408
       */
      LID_ID?: number;
      /**
       * @description De volledige naam van het lid
       * @example Meindert het Paard
       */
      VLIEGER?: string;
    };
    samenvatting: {
      /**
       * Format: int32
       * @description Aantal aanmeldingen voor de dag
       * @example 24
       */
      aanmeldingen?: number;
      /**
       * Format: int32
       * @description Aanwezige leden die mogen lieren
       * @example 8
       */
      lieristen?: number;
      /**
       * Format: int32
       * @description Instructeurs die zich aangemeld hebben voor de vliegdag
       * @example 5
       */
      instructeurs?: number;
      /**
       * Format: int32
       * @description Aanwezige leden die ook startleider zijn
       * @example 0
       */
      startleiders?: number;
      /**
       * Format: int32
       * @description Aantal DBO'ers
       * @example 4
       */
      dbo?: number;
      /**
       * Format: int32
       * @description Aantal solisten
       * @example 6
       */
      solisten?: number;
      /**
       * Format: int32
       * @description Aantal vliegers met een brevet
       * @example 18
       */
      brevethouders?: number;
      types?: {
        /**
         * Format: int32
         * @description ID uit van vliegtuig type uit types tabel
         * @example 406
         */
        id?: number;
        /**
         * @description Omschrijving van het type
         * @example ASK 21
         */
        type?: string;
        /**
         * Format: int32
         * @example 0
         */
        aantal?: number;
      }[];
      overland?: {
        /**
         * @description Registratie & callsign van het vliegtuig waar het lid mee overland wil
         * @example PH-1126 (TV)
         */
        reg_call?: string;
        /** @example Dirk van Loon */
        naam?: string;
      }[];
    };
  };
}

export interface operations {}

export interface external {}
