/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/Daginfo/CreateTable": {
    post: {
      parameters: {
        query: {
          /** Dummy records aanmaken */
          FILLDATA: boolean;
        };
      };
      responses: {
        /** Aangemaakt, Tabel toegevoegd */
        201: unknown;
        /** Data verwerkingsfout, bijv omdat de tabel al bestaat */
        500: unknown;
      };
    };
  };
  "/Daginfo/CreateViews": {
    post: {
      responses: {
        /** Aangemaakt, View toegevoegd */
        201: unknown;
        /** Data verwerkingsfout, view niet aangemaak */
        500: unknown;
      };
    };
  };
  "/Daginfo/GetObject": {
    get: {
      parameters: {
        query: {
          /** Database ID van het daginfo record */
          ID?: number;
          /** Datum van de daginfo */
          DATUM?: string;
        };
      };
      responses: {
        /** OK, data succesvol opgehaald */
        200: {
          content: {
            "application/json": components["schemas"]["oper_daginfo"];
          };
        };
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/Daginfo/GetObjects": {
    get: {
      parameters: {
        query: {
          /** Database ID van het aanwezig record */
          ID?: number;
          /** Toon welke records verwijderd zijn. Default = false */
          VERWIJDERD?: boolean;
          /** Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg */
          LAATSTE_AANPASSING?: boolean;
          /** HASH van laatste GetObjects aanroep. Indien bij nieuwe aanroep dezelfde data bevat, dan volgt http status code 304. In geval dataset niet hetzelfde is, dan komt de nieuwe dataset terug. Ook bedoeld om dataverbruik te vermindereren. Er wordt alleen data verzonden als het nodig is. */
          HASH?: string;
          /** Sortering van de velden in ORDER BY formaat. Default = DATUM DESC */
          SORT?: string;
          /** Maximum aantal records in de dataset. Gebruikt in LIMIT query */
          MAX?: number;
          /** Eerste record in de dataset. Gebruikt in LIMIT query */
          START?: number;
          /** Welke velden moet opgenomen worden in de dataset */
          VELDEN?: string;
          /** Zoek op datum */
          DATUM?: string;
          /** Begin datum (inclusief deze dag) */
          BEGIN_DATUM?: string;
          /** Eind datum (inclusief deze dag) */
          EIND_DATUM?: string;
        };
      };
      responses: {
        /** OK, data succesvol opgehaald */
        200: {
          content: {
            "application/json": components["schemas"]["view_daginfo"];
          };
        };
        /** Data niet gemodificeerd, HASH in aanroep == hash in dataset */
        304: never;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/Daginfo/DeleteObject": {
    delete: {
      parameters: {
        query: {
          /** Database ID van het daginfo record. Meerdere ID's in CSV formaat */
          ID?: string;
          /** Datum van de daginfo */
          DATUM?: string;
          /** Controleer of record bestaat voordat het verwijderd wordt. Default = true */
          VERIFICATIE?: boolean;
        };
      };
      responses: {
        /** Daginfo verwijderd */
        204: never;
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/Daginfo/RestoreObject": {
    patch: {
      parameters: {
        query: {
          /** Database ID van het record. Meerdere ID's in CSV formaat */
          ID: string;
        };
      };
      responses: {
        /** Record(s) hersteld */
        202: unknown;
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/Daginfo/SaveObject": {
    put: {
      responses: {
        /** OK, data succesvol aangepast */
        200: {
          content: {
            "application/json": components["schemas"]["oper_daginfo"];
          };
        };
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Conflict, datum bestaat al */
        409: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
      /** Daginfo data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["oper_daginfo_in"];
        };
      };
    };
    post: {
      responses: {
        /** OK, data succesvol toegevoegd */
        200: {
          content: {
            "application/json": components["schemas"]["oper_daginfo"];
          };
        };
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Conflict, datum bestaat al */
        409: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
      /** Daginfo data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["oper_daginfo_in"];
        };
      };
    };
  };
}

export interface components {
  schemas: {
    oper_daginfo_in: {
      /** Database ID van het daginfo record */
      ID?: number;
      /** Datum van de vliegdag */
      DATUM?: string;
      /** Welke vliegveld vliegen we vandaag. Kan afwijken voor vliegkamp. Verwijzing naar type tabel. */
      VELD_ID?: number;
      /** Is het een DDWV dag? */
      DDWV?: boolean;
      /** Is er een clubbedrijf */
      CLUB_BEDRIJF?: boolean;
      /** Incidenten om iets van te leren */
      INCIDENTEN?: string;
      /** Beschrijving van de situatie op het veld */
      VLIEGBEDRIJF?: string;
      /** Beschrijving van de weerscondities */
      METEO?: string;
      /** Aanwezigheid van functionarissen */
      DIENSTEN?: string;
      /** Kort veslag van de dag */
      VERSLAG?: string;
      /** Opmerkingen over het rollend materieel */
      ROLLENDMATERIEEL?: string;
      /** Opmerkingen over de vloot */
      VLIEGENDMATERIEEL?: string;
    } & { [key: string]: any };
    oper_daginfo: components["schemas"]["oper_daginfo_in"] &
      ({
        /** Is dit record gemarkeerd als verwijderd? */
        VERWIJDERD?: boolean;
        /** Tijdstempel van laaste aanpassing in de database, laat leeg bij updates */
        LAATSTE_AANPASSING?: string;
      } & { [key: string]: any }) & { [key: string]: any };
    view_daginfo_dataset: components["schemas"]["oper_daginfo"] &
      ({
        /** Verkorte naam van het vliegveld */
        VELD_CODE?: string;
        /** Naam van het vliegveld */
        VELD_OMS?: string;
        /** Verkorte beschrijving start strip */
        BAAN_CODE?: string;
        /** beschrijving start strip */
        BAAN_OMS?: string;
        /** Verkorte naam van de club die leiding heeft over vliegbedrijf */
        BEDRIJF_CODE?: string;
        /** Club die leiding heeft over vliegbedrijf */
        BEDRIJF_OMS?: string;
        /** De verkorte beschrijving van de meest gebruikte startmethode */
        STARTMETHODE_CODE?: string;
        /** Beschrijving van de meest gebruikte startmethode */
        STARTMETHODE_OMS?: string;
      } & { [key: string]: any }) & { [key: string]: any };
    view_daginfo: {
      /** Aantal records dat voldoet aan de criteria in de database */
      totaal?: number;
      /** Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria */
      laatste_aanpassing?: string;
      /** hash van de dataset */
      hash?: string;
      /** De dataset met records */
      dataset?: components["schemas"]["view_daginfo_dataset"][];
    } & { [key: string]: any };
  };
}

export interface operations {}
