/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/DagRapporten/CreateTable": {
    post: {
      parameters: {
        query: {
          /** Dummy records aanmaken */
          FILLDATA: boolean;
        };
      };
      responses: {
        /** Aangemaakt, Tabel toegevoegd */
        201: unknown;
        /** Data verwerkingsfout, bijv omdat de tabel al bestaat */
        500: unknown;
      };
    };
  };
  "/DagRapporten/CreateViews": {
    post: {
      responses: {
        /** Aangemaakt, View toegevoegd */
        201: unknown;
        /** Data verwerkingsfout, view niet aangemaak */
        500: unknown;
      };
    };
  };
  "/DagRapporten/GetObject": {
    get: {
      parameters: {
        query: {
          /** Database ID van het dag rapport record */
          ID?: number;
        };
      };
      responses: {
        /** OK, data succesvol opgehaald */
        200: {
          content: {
            "application/json": components["schemas"]["oper_dagrapport"];
          };
        };
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/DagRapporten/GetObjects": {
    get: {
      parameters: {
        query: {
          /** Database ID van het dag rapport record */
          ID?: number;
          /** Toon welke records verwijderd zijn. Default = false */
          VERWIJDERD?: boolean;
          /** Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg */
          LAATSTE_AANPASSING?: boolean;
          /** HASH van laatste GetObjects aanroep. Indien bij nieuwe aanroep dezelfde data bevat, dan volgt http status code 304. In geval dataset niet hetzelfde is, dan komt de nieuwe dataset terug. Ook bedoeld om dataverbruik te vermindereren. Er wordt alleen data verzonden als het nodig is. */
          HASH?: string;
          /** Sortering van de velden in ORDER BY formaat. Default = DATUM DESC */
          SORT?: string;
          /** Maximum aantal records in de dataset. Gebruikt in LIMIT query */
          MAX?: number;
          /** Eerste record in de dataset. Gebruikt in LIMIT query */
          START?: number;
          /** Welke velden moet opgenomen worden in de dataset */
          VELDEN?: string;
          /** Zoek op datum */
          DATUM?: string;
          /** Begin datum (inclusief deze dag) */
          BEGIN_DATUM?: string;
          /** Eind datum (inclusief deze dag) */
          EIND_DATUM?: string;
        };
      };
      responses: {
        /** OK, data succesvol opgehaald */
        200: {
          content: {
            "application/json": components["schemas"]["view_dagrapporten"];
          };
        };
        /** Data niet gemodificeerd, HASH in aanroep == hash in dataset */
        304: never;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/DagRapporten/DeleteObject": {
    delete: {
      parameters: {
        query: {
          /** Database ID van het dag rapport record. Meerdere ID's in CSV formaat */
          ID?: string;
          /** Controleer of record bestaat voordat het verwijderd wordt. Default = true */
          VERIFICATIE?: boolean;
        };
      };
      responses: {
        /** Dag rapport verwijderd */
        204: never;
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/DagRapporten/RestoreObject": {
    patch: {
      parameters: {
        query: {
          /** Database ID van het record. Meerdere ID's in CSV formaat */
          ID: string;
        };
      };
      responses: {
        /** Record(s) hersteld */
        202: unknown;
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
    };
  };
  "/DagRapporten/SaveObject": {
    put: {
      responses: {
        /** OK, data succesvol aangepast */
        200: {
          content: {
            "application/json": components["schemas"]["oper_dagrapport"];
          };
        };
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Data niet gevonden */
        404: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Conflict, datum bestaat al */
        409: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
      /** Dag rapport data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["oper_dagrapport_in"];
        };
      };
    };
    post: {
      responses: {
        /** OK, data succesvol toegevoegd */
        200: {
          content: {
            "application/json": components["schemas"]["oper_dagrapport"];
          };
        };
        /** Niet geautoriseerd, geen schrijfrechten */
        401: unknown;
        /** Methode niet toegestaan, input validatie error */
        405: unknown;
        /** Niet aanvaardbaar, input ontbreekt */
        406: unknown;
        /** Conflict, datum bestaat al */
        409: unknown;
        /** Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
        500: unknown;
      };
      /** Dag rapport data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["oper_dagrapport_in"];
        };
      };
    };
  };
}

export interface components {
  schemas: {
    oper_dagrapport_in: {
      /**
       * Format: int32
       * @description Database ID van het dag rapport record
       * @example 12871
       */
      ID?: number;
      /**
       * Format: date
       * @description Datum van het dagrapport
       * @example 2017-07-21
       */
      DATUM?: string;
      /**
       * Format: int32
       * @description Voor welk vliegveld is dit dagrapport van toepassing
       * @example 901
       */
      VELD_ID?: number;
      /**
       * @description Incidenten om iets van te leren
       * @example Scherpe uitstekels aan lierkabel
       */
      INCIDENTEN?: string;
      /**
       * @description Beschrijving van de situatie op het veld
       * @example Het vliegbedrijf bevatte de volgende aspect(en), lier, sleep en zelfstart op de 22R met een rechterhand circuit. Halverwege de dag omgesteld naar 27C
       */
      VLIEGBEDRIJF?: string;
      /**
       * @description Beschrijving van de weerscondities
       * @example Het zicht was > 10 km. De windrichting was 270 met  windkracht 3.4 - 5.42 m/s. Er was 2/8 bewolking. De wolkenbasis was 800 meter hoog.
       */
      METEO?: string;
      /**
       * @description Kort veslag van de dag
       * @example Rustige dag met een klein ploegje mensen ondanks het prachtige weer. Omstellen ging zonder problemen, vliegende kisten konden blijven hangen
       */
      VERSLAG?: string;
      /**
       * @description Opmerkingen over het rollend materieel
       * @example De motor van de lier wordt warm
       */
      ROLLENDMATERIEEL?: string;
      /**
       * @description Opmerkingen over de vloot
       * @example De E11 is in de werkplaats gezet ivm lekke band. Wordt maandag opgelost
       */
      VLIEGENDMATERIEEL?: string;
    };
    oper_dagrapport: components["schemas"]["oper_dagrapport_in"] & {
      /**
       * Format: int32
       * @description ID van instructeur die heeft ingevoerd (wordt op de server gezet)
       * @example 10390
       */
      INGEVOERD_ID?: number;
      /**
       * @description Is dit record gemarkeerd als verwijderd?
       * @example 0
       */
      VERWIJDERD?: boolean;
      /**
       * Format: date-time
       * @description Tijdstempel van laaste aanpassing in de database, laat leeg bij updates
       * @example 2010-04-13 19:32:17
       */
      LAATSTE_AANPASSING?: string;
    };
    view_dagrapporten_dataset: components["schemas"]["oper_dagrapport"] & {
      /**
       * @description Verkorte naam van het vliegveld
       * @example EHTL
       */
      VELD_CODE?: string;
      /**
       * @description Naam van het vliegveld
       * @example Terlet
       */
      VELD_OMS?: string;
      /**
       * @description Naam van de instructeur die dagrapport heeft gemaakt
       * @example Momfert de mol
       */
      INGEVOERD?: string;
    };
    view_dagrapporten: {
      /**
       * Format: int32
       * @description Aantal records dat voldoet aan de criteria in de database
       * @example 287
       */
      totaal?: number;
      /**
       * Format: date-time
       * @description Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria
       * @example 2020-09-01 06:00:05
       */
      laatste_aanpassing?: string;
      /**
       * @description hash van de dataset
       * @example ddaab00
       */
      hash?: string;
      /** @description De dataset met records */
      dataset?: components["schemas"]["view_dagrapporten_dataset"][];
    };
  };
}

export interface operations {}

export interface external {}
