/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/Login/GetUserInfo": {
    get: {
      parameters: {
        query: {
          /** De datum waarop isStartleider bepaald is. Indien afwezig, dan de dag van vandaag */
          DATUM?: string;
        };
      };
      responses: {
        /** OK, data succesvol opgehaald */
        200: {
          content: {
            "application/json": components["schemas"]["Userinfo"];
          };
        };
        /** Data niet gevonden */
        404: unknown;
      };
    };
  };
  "/Login/Login": {
    get: {
      parameters: {
        query: {
          /** 2factor token */
          token?: string;
        };
      };
      responses: {
        /** OK, ingelogd */
        200: unknown;
        /** Mislukt */
        401: unknown;
      };
    };
  };
  "/Login/Logout": {
    get: {
      responses: {
        /** OK, tot de volgende keer */
        200: unknown;
      };
    };
  };
}

export interface components {
  schemas: {
    ref_leden: {
      /** Database ID van het lid record */
      ID?: number;
      /** De volledige naam van het lid */
      NAAM?: string;
      /** De voornaam van het lid */
      VOORNAAM?: string;
      /** De achternaam van het lid zonder voorvoegsels */
      ACHTERNAAM?: string;
      /** Telefoon nummer van het lid */
      TELEFOON?: string;
      /** Mobiel telefoon nummer van het lid */
      MOBIEL?: string;
      /** Het telefoonnummer van een naaste, kan gebruikt worden in noodgevallen */
      NOODNUMMER?: string;
      /** email adres van het lid */
      EMAIL?: string;
      /** Het lidnummer zoals dat in de leden administratie bekend is */
      LIDNR?: string;
      /** Het soort lid (jeugdlid, lid, donateur). Verwijzing naar type tabel */
      LIDTYPE_ID?: number;
      /** Mag dit lid lieren? Waarde 0..1 */
      LIERIST?: boolean;
      /** Kan dit lid het startbedrijf leiden?  Waarde 0..1 */
      STARTLEIDER?: boolean;
      /** Heeft dit lid een instructie bevoegdheid?  Waarde 0..1 */
      INSTRUCTEUR?: boolean;
      /** De inlognaam van het lid */
      INLOGNAAM?: string;
      /** Het geheime password */
      WACHTWOORD?: string;
      /** Heef het lid de factuur van dit jaar betaald?  Waarde 0..1 */
      HEEFT_BETAALD?: boolean;
      /** Staat privacy mode (AVG / GDPR) uit/aan Waarde 0..1 */
      PRIVACY?: boolean;
      /** Is dit record gemarkeerd als verwijderd?  Waarde 0..1 */
      VERWIJDERD?: boolean;
      /** Tijdstempel van laaste aanpassing in de database */
      LAATSTE_AANPASSING?: string;
    } & { [key: string]: any };
    Userinfo: {
      /** Aantal records dat voldoet aan de criteria in de database */
      LidData?: components["schemas"]["ref_leden"];
      /** Gebruik dit object voor applicatie permissies */
      Userinfo?: {
        /** Datum, isStartleider ben je namelijk alleen op de dag dat je dienst hebt */
        DATUM?: string;
        /** Mag de ingelode gebruiker schrijven in de database */
        magSchrijven?: boolean;
        /** Is de ingelogde gebruiker de DDWV beheerder */
        isBeheerderDDWV?: boolean;
        /** Is de ingelogde gebruiker de applicatie beheerder */
        isBeheerder?: boolean;
        /** Is de ingelogde gebruiker een startleider (alleen op de dag zelf) */
        isStartleider?: boolean;
        /** Is de ingelogde gebruiker de rooster maker */
        isRooster?: boolean;
        /** Is de ingelogde gebruiker een instructeur */
        isInstructeur?: boolean;
        /** Is de ingelogde gebruiker chef instructeur */
        isCIMT?: boolean;
        /** Is de ingelogde gebruiker de starttoren? */
        isStarttoren?: boolean;
        /** Is de ingelogde gebruiker aangemeld voor vandaag */
        isAangemeld?: boolean;
        /** Is de ingelogde gebruiker een lid van de club */
        isClubVlieger?: boolean;
        /** Is de ingelogde gebruiker een DDWV vlieger (dus geen club lid) */
        isDDWV?: boolean;
      } & { [key: string]: any };
    } & { [key: string]: any };
  };
}

export interface operations {}
