# This workflow will do a clean installation of node dependencies, build the source code and run linter across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular Build

# This build must run for every push to any branch, and for every pull request to any branch. Additionally, it must run for every manual trigger.
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Because package-lock.json is in the .gitignore we cannot use `npm ci` (clean-install). But since the package-lock.json is missing, regular `npm install` will do the same thing :)
      - run: npm i
        name: Install Dependencies

      - run: npm run build
        name: Run Build

      - run: npm run lint
        name: Run Linting

      - run: npm run test:ci
        name: Run Tests
